linters:
  enable-all: true
  disable:
    - gochecknoglobals # usually just false positives
    - maligned # deprecated
    - scopelint # deprecated
    - paralleltest # lots of code, little gain; prefer using t.Parallel() only for slow tests
    - exhaustivestruct # just a pain, not too useful
    - goconst # finds repeated strings >= 3 times; but usually that's OK
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true # enable "default"-case in switch as catch-all for all other options

issues:
  max-per-linter: 0 # default is 50, 0 = disable
  max-same-issues: 0 # default is 3, 0 = disable

output:
  sort-results: true