name: Test
on: push
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'

      - name: Run tests
        run: make test
